### ISSUE TITLE
Give meaningfull error messages when the root cause is unsuccessful authentification

### ISSUE THREAD

**Issue by pdo-be** [plantpredict/python-sdk#1]
I'm trying to get starting with the PlantPredict API, and it seems that my API credentials are not being accepted. When this happens, the python class would do well to throw an error that points the user towards this root cause. Instead, the code gives a rather opque error, that does not seem directly related to authentification. 

The error handling doesn't have to be fancy, as a start I added this to Api.__get_access_token(self):

        except KeyError:
            print("Authentification failed. Response:", response.text)
            pass

**Comment by jessemilam** [comment]
Thank you for the suggestion, this would be a quality addition. I've committed the changes to the master branch and this will be included in the next release.
